all:
	$(MAKE) -C src -f Makefile.Octeon

clean:
	$(MAKE) -C src clean -f Makefile.Octeon
	$(MAKE) -C 3rdParty/libxml2 distclean
	unlink Makefile

install: src-install

src-install:
	$(MAKE) -C src install -f Makefile.Octeon

un-install:
	$(MAKE) -C src/httpd un-install -f Makefile.Octeon
