make clean
./version.sh
gcc -O2  -Wall -Waggregate-return -Wcast-align -Wcast-qual -Wcomment -Wformat -Wimplicit-int  -Wimplicit-function-declaration -Winline -Wlong-long -Wmain -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Wno-import  -Wparentheses -Wpointer-arith -Wredundant-decls -Wreturn-type -Wswitch -Wunused  -Wunused-function -Wunused-label -Wunused-parameter -Wunused-variable -Wunused-value -fPIC -Werror -I/usr/local/wdir/EasyAccess/src/lib -c -o libsslcert.o libsslcert.c
gcc -O2  -Wall -Waggregate-return -Wcast-align -Wcast-qual -Wcomment -Wformat -Wimplicit-int  -Wimplicit-function-declaration -Winline -Wlong-long -Wmain -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Wno-import  -Wparentheses -Wpointer-arith -Wredundant-decls -Wreturn-type -Wswitch -Wunused  -Wunused-function -Wunused-label -Wunused-parameter -Wunused-variable -Wunused-value -fPIC -Werror -I/usr/local/wdir/EasyAccess/src/lib -c -o lscrsa.o lscrsa.c
gcc -O2  -Wall -Waggregate-return -Wcast-align -Wcast-qual -Wcomment -Wformat -Wimplicit-int  -Wimplicit-function-declaration -Winline -Wlong-long -Wmain -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Wno-import  -Wparentheses -Wpointer-arith -Wredundant-decls -Wreturn-type -Wswitch -Wunused  -Wunused-function -Wunused-label -Wunused-parameter -Wunused-variable -Wunused-value -fPIC -Werror -I/usr/local/wdir/EasyAccess/src/lib -c -o lscrand.o lscrand.c
gcc -O2  -Wall -Waggregate-return -Wcast-align -Wcast-qual -Wcomment -Wformat -Wimplicit-int  -Wimplicit-function-declaration -Winline -Wlong-long -Wmain -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Wno-import  -Wparentheses -Wpointer-arith -Wredundant-decls -Wreturn-type -Wswitch -Wunused  -Wunused-function -Wunused-label -Wunused-parameter -Wunused-variable -Wunused-value -fPIC -Werror -I/usr/local/wdir/EasyAccess/src/lib -c -o lscCertReq.o lscCertReq.c
gcc -O2  -Wall -Waggregate-return -Wcast-align -Wcast-qual -Wcomment -Wformat -Wimplicit-int  -Wimplicit-function-declaration -Winline -Wlong-long -Wmain -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Wno-import  -Wparentheses -Wpointer-arith -Wredundant-decls -Wreturn-type -Wswitch -Wunused  -Wunused-function -Wunused-label -Wunused-parameter -Wunused-variable -Wunused-value -fPIC -Werror -I/usr/local/wdir/EasyAccess/src/lib -c -o lscx509.o lscx509.c
/bin/rm -f libsslcert.a
ar cq libsslcert.a libsslcert.o lscrsa.o lscrand.o lscCertReq.o
/usr/bin/ranlib libsslcert.a
/usr/bin/strip libsslcert.a
