SOURCES=libsslcert.o	\
	lscrsa.o	\
	lscrand.o	\
	lscCertReq.o	\
	lscx509.o

LIB=libsslcert.a

include ../make-include-uClinux.mk

CFLAGS+=	-I$(SYS_LIB)		\
		-ULSC_DEBUG_ASSERT	\
		-ULSC_DEBUG_LOG		\
		-ULSC_OPENSSL_DEBUG	\
		-ULSC_LOG_TARGET=stderr

all: $(LIB)

$(LIB): $(SOURCES) 
	$(AR) cr $(LIB) $(SOURCES)

cleanbin: 
	rm $(BIN)
	if [ -n '$(LIB)' ]; then rm -rf $(LIB); fi

clean:
	rm -f *.o
	rm -f $(BIN)
	if [ -n '$(LIB)' ]; then rm -rf $(LIB); fi

install:

un-install:
