
install:
	cp ./named ${ROOT}/sbin
#	rm -rf ${ROOT}/var/named
#	rm -rf ${ROOT}/etc/named
#	-mkdir ${ROOT}/var/named
#	-mkdir ${ROOT}/etc/named
#	cp ./named1.conf ${ROOT}/etc/named
#	cp ./gavintest.com.internal ${ROOT}/etc/named
#	cp ./gavintest.com.external ${ROOT}/etc/named

clean:

